name: Release and Publish
on:
  workflow_dispatch:
  push:
    branches: ['main']

jobs:
  publish-tauri:
    name: Publish new version
    permissions: write-all
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: honey-player/desktop-app
          token: ${{ secrets.APP_GITHUB_TOKEN }}
          ref: main
      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Setup Cargo Cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
      - name: Install Pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.2.0
          run_install: false
      - name: Setup Pnpm Cache
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
      - name: Install app dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Package the server
        run: pnpm package
      - name: Bundle the build
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: app-v__VERSION__
          releaseName: 'Honey Player v__VERSION__'
          releaseBody: 'Take a look at the assets to download and install this app.'
          releaseDraft: false
          includeUpdaterJson: true
          prerelease: true
